// ============================================================================
// Opponent configuration — the 8 story-mode opponents as pure data.
// engine.ts imports OPPONENTS from here.
// ============================================================================

import type { OpponentDef } from "../types";

export const OPPONENTS: OpponentDef[] = [
  {
    name: "Lynx",
    title: "The Last Apprentice",
    rim: "#f59e0b",
    hp: 70,
    damageMul: 0.55,
    speedMul: 0.85,
    aggression: 0.34,
    blockChance: 0.08,
    reaction: 0.55,
    combo: 1,
    bg: "sunset",
    bodyType: "lean",
    story: "The youngest of the order. He does not yet know the hero he hunts is already dead.",
    whiffPunish: 0.05,
    antiAir: 0.04,
    pressure: 0.1,
    mixup: 0.05,
    adaptive: 0.05,
    rage: 0.1,
    perfection: 0.0,
  },
  {
    name: "Bandit",
    title: "The Defector",
    rim: "#fbbf24",
    hp: 84,
    damageMul: 0.68,
    speedMul: 0.95,
    aggression: 0.44,
    blockChance: 0.14,
    reaction: 0.44,
    combo: 2,
    bg: "desert",
    bodyType: "lean",
    story: "Once a shadow-touched blade, now turned sealer. He remembers what you are.",
    whiffPunish: 0.15,
    antiAir: 0.12,
    pressure: 0.2,
    mixup: 0.12,
    adaptive: 0.12,
    rage: 0.15,
    perfection: 0.0,
  },
  {
    name: "Crane",
    title: "The Temple Guard",
    rim: "#2dd4bf",
    hp: 100,
    damageMul: 0.82,
    speedMul: 1.0,
    aggression: 0.54,
    blockChance: 0.26,
    reaction: 0.32,
    combo: 2,
    bg: "temple",
    bodyType: "tall",
    story: "He forged the first chains that bound your kind. His guard is absolute.",
    whiffPunish: 0.3,
    antiAir: 0.25,
    pressure: 0.32,
    mixup: 0.22,
    adaptive: 0.25,
    rage: 0.22,
    perfection: 0.05,
  },
  {
    name: "Hermit",
    title: "The Hermit",
    rim: "#84cc16",
    hp: 114,
    damageMul: 0.94,
    speedMul: 1.06,
    aggression: 0.62,
    blockChance: 0.32,
    reaction: 0.26,
    combo: 3,
    bg: "bamboo",
    bodyType: "hunched",
    story: "He taught the dead swordsman everything. Now he teaches you fear.",
    whiffPunish: 0.45,
    antiAir: 0.4,
    pressure: 0.45,
    mixup: 0.35,
    adaptive: 0.4,
    rage: 0.3,
    perfection: 0.12,
  },
  {
    name: "Widow",
    title: "The Nightblade",
    rim: "#e879f9",
    hp: 118,
    damageMul: 1.0,
    speedMul: 1.12,
    aggression: 0.68,
    blockChance: 0.4,
    reaction: 0.2,
    combo: 3,
    bg: "moon",
    bodyType: "lean",
    story: "She moves between heartbeats. By the time you see her, she has already struck.",
    whiffPunish: 0.55,
    antiAir: 0.5,
    pressure: 0.55,
    mixup: 0.45,
    adaptive: 0.55,
    rage: 0.35,
    perfection: 0.2,
  },
  {
    name: "Butcher",
    title: "The Colossus",
    rim: "#ef4444",
    hp: 140,
    damageMul: 1.1,
    speedMul: 0.92,
    aggression: 0.74,
    blockChance: 0.34,
    reaction: 0.22,
    combo: 3,
    bg: "volcano",
    bodyType: "bulky",
    story: "He does not feel pain. He does not stop. He is the wall that breaks armies.",
    whiffPunish: 0.5,
    antiAir: 0.45,
    pressure: 0.7,
    mixup: 0.4,
    adaptive: 0.45,
    rage: 0.4,
    perfection: 0.25,
  },
  {
    name: "Shogun",
    title: "The Shogun",
    rim: "#c084fc",
    hp: 130,
    damageMul: 1.05,
    speedMul: 1.0,
    aggression: 0.78,
    blockChance: 0.5,
    reaction: 0.16,
    combo: 3,
    bg: "snow",
    bodyType: "tall",
    story: "His defense is a fortress. His offense is a storm. He has never lost.",
    whiffPunish: 0.65,
    antiAir: 0.55,
    pressure: 0.65,
    mixup: 0.55,
    adaptive: 0.6,
    rage: 0.45,
    perfection: 0.4,
  },
  {
    name: "Titan",
    title: "The World's Last Hope",
    rim: "#f87171",
    hp: 160,
    damageMul: 1.2,
    speedMul: 1.05,
    aggression: 0.84,
    blockChance: 0.56,
    reaction: 0.13,
    combo: 3,
    bg: "moon",
    bodyType: "bulky",
    story: "The last sealer. Defeat him, and the gates are yours to open — forever.",
    whiffPunish: 0.88,
    antiAir: 0.82,
    pressure: 0.82,
    mixup: 0.78,
    adaptive: 0.85,
    rage: 0.7,
    perfection: 0.55,
  },
];
